server:
  port: ${services.clouddriver.port:7002}
  address: 0.0.0.0

redis:
  connection: ${services.redis.connection:redis://localhost:6379}

default:
  account:
    env: ${providers.kubernetes.primaryCredentials.name}

kubernetes:
  enabled: true
  accounts:
    - name: my-kubernetes-account
      namespaces:
        - default
        - _{install-namespace}
      dockerRegistries:
        - accountName: my-gcr-account

dockerRegistry:
  enabled: true
  accounts:
    - name: my-gcr-account
      address: https://gcr.io
      repositories:
        - library/nginx

credentials:
  primaryAccountTypes: ${providers.kubernetes.primaryCredentials.name}
  challengeDestructiveActionsEnvironments: ${providers.kubernetes.primaryCredentials.name}
