server:
  port: ${services.clouddriver.port:7002}
  address: 0.0.0.0

redis:
  connection: ${services.redis.connection:redis://localhost:6379}

default:
  account:
    env: ${providers.kubernetes.primaryCredentials.name}

kubernetes:
  enabled: true
  accounts:
    - name: my-kubernetes-account
      dockerRegistries: # WARNING! only include configured accounts here
        - accountName: my-dockerhub-account 

dockerRegistry:
  enabled: true
  accounts:
    - name: my-dockerhub-account
      address: https://index.docker.io
      username: {%username%}
      password: {%password%}
      repositories:
        - {%username%}/{%image%}

credentials:
  primaryAccountTypes: ${providers.kubernetes.primaryCredentials.name}
  challengeDestructiveActionsEnvironments: ${providers.kubernetes.primaryCredentials.name}
